import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "./components/layout/Header";
import Footer from "./components/layout/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-[#161717]">
       <body className={`${geistSans.variable} ${geistMono.variable}  antialiased min-h-screen bg-[#0b0c0e] flex flex-col`}>
        <Header />

        <main className="flex-1 -mt-15 mb-5 md:mt-0">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
